const counties= [
  { "code": "001", "county": "Mombasa" },
  { "code": "002", "county": "Kwale" },
  { "code": "003", "county": "Kilifi" },
  { "code": "004", "county": "Tana River" },
  { "code": "005", "county": "Lamu" },
  { "code": "006", "county": "Taita–Taveta" },
  { "code": "007", "county": "Garissa" },
  { "code": "008", "county": "Wajir" },
  { "code": "009", "county": "Mandera" },
  { "code": "010", "county": "Marsabit" },
  { "code": "011", "county": "Isiolo" },
  { "code": "012", "county": "Meru" },
  { "code": "013", "county": "Tharaka-Nithi" },
  { "code": "014", "county": "Embu" },
  { "code": "015", "county": "Kitui" },
  { "code": "016", "county": "Machakos" },
  { "code": "017", "county": "Makueni" },
  { "code": "018", "county": "Nyandarua" },
  { "code": "019", "county": "Nyeri" },
  { "code": "020", "county": "Kirinyaga" },
  { "code": "021", "county": "Murang'a" },
  { "code": "022", "county": "Kiambu" },
  { "code": "023", "county": "Turkana" },
  { "code": "024", "county": "West Pokot" },
  { "code": "025", "county": "Samburu" },
  { "code": "026", "county": "Trans-Nzoia" },
  { "code": "027", "county": "Uasin Gishu" },
  { "code": "028", "county": "Elgeyo-Marakwet" },
  { "code": "029", "county": "Nandi" },
  { "code": "030", "county": "Baringo" },
  { "code": "031", "county": "Laikipia" },
  { "code": "032", "county": "Nakuru" },
  { "code": "033", "county": "Narok" },
  { "code": "034", "county": "Kajiado" },
  { "code": "035", "county": "Kericho" },
  { "code": "036", "county": "Bomet" },
  { "code": "037", "county": "Kakamega" },
  { "code": "038", "county": "Vihiga" },
  { "code": "039", "county": "Bungoma" },
  { "code": "040", "county": "Busia" },
  { "code": "041", "county": "Siaya" },
  { "code": "042", "county": "Kisumu" },
  { "code": "043", "county": "Homa Bay" },
  { "code": "044", "county": "Migori" },
  { "code": "045", "county": "Kisii" },
  { "code": "046", "county": "Nyamira" },
  { "code": "047", "county": "Nairobi" }
]

  export default counties;